language: node_js
node_js:
  - "10"
sudo: required  
addons:
  chrome: stable  
  sauce_connect: true
before_script:
  - npm install -g codecov
  - npm install -g @liriliri/lsla
script:
  - npm run ci
after_script:
  - codecov --disable=gcov 
